apiVersion: v1
kind: ServiceAccount
metadata:
  name: conjur-aws-java-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::179196310045:role/bnl-eks-pod-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conjur-aws-java
  namespace: bnl-demo-app-ns
  labels:
    app: conjur-aws-java
spec:
  selector:
    matchLabels:
      app: conjur-aws-java
  replicas: 1
  template:
    metadata:
      labels:
        app: conjur-aws-java
    spec:
      serviceAccountName: conjur-aws-java-sa
      containers:
        - name: conjur-aws-java
          image: bnasslahsen/conjur-aws-java
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: conjur-connect-aws-java

